language: node_js
node_js: 
 â€” "6"
 jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=dbotia-github -Dsonar.projectKey=micalc -Dsonar.sources='./app' -X
